/*
  Warnings:

  - You are about to drop the column `description` on the `Symptoms` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "symptomsDescription" AS ENUM ('ABD_SENSIVEL_RIGIDO', 'AFUNDAMENTO_DE_CRANIO', 'AGITACAO', 'AMNESIA', 'ANGINA_DE_PEITO', 'APINEIA', 'BRADICARDIA', 'BRADIPNEIA', 'BRONCO_ASPIRANDO', 'CEFALIA', 'CIANOSE_LABIOS', 'CIANOSE_EXTREMIDADES', 'CONVULSAO', 'DECORTICACAO', 'DEFORMIDADE', 'DESCEREBRACAO', 'DESMAIO', 'DESVIO_DE_TRAQUEIA', 'DISPNEIA', 'DOR_LOCAL', 'EDEMA_GENERALIZADO', 'EDEMA_LOCALIZADO', 'ENFISEMA_SUBCUTANEO', 'ESTASE_DA_JUGULAR', 'FACE_PALIDA', 'HEMORRAGIA_INTERNA', 'HEMORRAGIA_EXTERNA', 'HIPERTENSAO', 'HIPOTENSAO', 'NAUSEAS_VOMITOS', 'NASORAGIA', 'OBITO', 'OTORREIA', 'OTORRAGIA', 'OVACE', 'PARADA_CARDIACA', 'PARADA_RESPIRATORIA', 'PRIAPRISMO', 'PRURIDO_NA_PELE', 'ANISOCORIA_NAO_REAGENTE', 'ANISOCORIA_REAGENTE', 'ISOCORIA_NAO_REAGENTE', 'ISOCORIA_REAGENTE', 'MIDRIASE_NAO_REAGENTE', 'MIDRIASE_REAGENTE', 'MIOSE_NAO_REAGENTE', 'MIOSE_REAGENTE', 'SEDE', 'SINAL_DE_BATTLE', 'SINAL_DE_GUAXINIM', 'SUDORESE', 'TAQUIPNEIA', 'TAQUICARDIA', 'TONTURA');

-- AlterTable
ALTER TABLE "Symptoms" DROP COLUMN "description",
ADD COLUMN     "symptomsDescription" TEXT[] DEFAULT ARRAY['']::TEXT[];
