'use client'

import AuthChecker from '@/middleware/authChecker'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SnackbarProvider } from 'notistack'
import store from '@/redux/stores/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Registrar bombeiros',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className} style={{ height: '100vh' }}>
        <Provider store={store}>
          <SnackbarProvider
            anchorOrigin={{
              vertical: 'bottom',
              horizontal: 'right',
            }}
          >
            <AuthChecker>{children}</AuthChecker>
          </SnackbarProvider>
        </Provider>
      </body>
    </html>
  )
}
