// TODO:
/**
 * aval. inicial,
 * compressivo,
 * limpeza de ferimento,
 * curativos,
 * imobilizações,
 * membro inf/sup/esq/dir,
 * maca rígida,
 * maca sobre rodas,
 * retirado capacete,
 * rolamento 90°,
 * rolamento 180°
 */

// TODO:
/**
 * Aspiração,
 * aval. dirigida,
 * aval. continuada,
 * chave de rautek,
 * cânula de guedel,
 * desobstrução de V. A.,
 * emprego do D.E.A.,
 * Geren. de riscos,
 * encravamento,
 * ocular,
 * queimadura,
 * simples,
 * 3 pontas,
 * quadril,
 * cervical,
 * ponte,
 * R.C.P.,
 * tomada decisão,
 * tratado choque,
 * uso de cânula,
 * uso colar,
 * uso KED,
 * uso TTF,
 * ventilação suporte,
 * oxigenoterapia (LPM),
 * reanimador (LPM),
 * meios auxiliares,
 * celesc,
 * def. civil,
 * IGPPC,
 * samu,
 * usa,
 * sub,
 * cit,
 * policia civil,
 * policia militar,
 * PRE,
 * PRF,
 * outro
 */
