import { z } from 'zod'

export const registerGestacionalAnamnese = z.object({
  gestationalPeriod: z.string().optional().nullable(),
  PreNatal: z.boolean().optional(),
  DoctorName: z.string().optional(),
  Complications: z.boolean().optional(),
  NumberSon: z.number().optional(),
  ContractionSchedule: z.string().optional().nullable(),
  Duration: z.string().optional().nullable(),
  Interval: z.string().optional().nullable(),
  HiPressure: z.boolean().optional().nullable(),
  BagRuptured: z.boolean().optional(),
  VisualInspection: z.boolean().optional(),
  Childbirth: z.boolean().optional(),
  BabyGender: z.string().optional(),
  BornHour: z.string().optional(),
  BabyName: z.string().optional(),
  FinalRemarks: z.string().optional(),
  ReportOwnerId: z.number(),
})

export const updateGestacionalAnamnese = z.object({
  gestationalPeriod: z.string().optional(),
  PreNatal: z.boolean().optional(),
  DoctorName: z.string().optional(),
  Complications: z.boolean().optional(),
  NumberSon: z.number().optional(),
  ContractionSchedule: z.string().optional(),
  Duration: z.string().optional(),
  Interval: z.string().optional(),
  HiPressure: z.boolean().optional(),
  BagRuptured: z.boolean().optional(),
  VisualInspection: z.boolean().optional(),
  Childbirth: z.boolean().optional(),
  BabyGender: z.string().optional(),
  BornHour: z.string().optional(),
  BabyName: z.string().optional(),
  FinalRemarks: z.string().optional(),
  ReportOwnerId: z.number().optional(),
})
