import { z } from 'zod'

export const registerInfosHospitalares = z.object({
  reportId: z.number(),
  Doctor: z.string().optional(),
  S1: z.string().optional(),
  S2: z.string().optional(),
  S3: z.string().optional(),
  Demandant: z.string().optional(),
  TeamUp: z.string().optional(),
  ProcedimentosEfetuados: z.object({
    state: z.boolean().nullable(),
    name: z.enum([
      'ASPIRACAO',
      'AVALIACAO_INICIAL',
      'AVALIACAO_DIRIGIDA',
      'AVALIACAO_CONTINUADA',
      'CHAVE_DE_RAUTEK',
      'CANULA_DE_GUEDEL',
      'DESOBSTRUCAO_DE_VA',
      'EMPREGO_DO_DEA',
      'GERENCIAMENTO_DE_RISCOS',
      'LIMPEZA_DE_FERIMENTO',
      'CURATIVOS',
      'COMPRESSIVO',
      'ENCRAVAMENTO',
      'OCULAR',
      'QUEIMADURA',
      'SIMPLES',
      'THREE_PONTAS',
      'IMOBILIZACOES',
      'MEMBRO_INF_DIR',
      'MEMBRO_INF_ESQ',
      'MEMBRO_SUP_DIR',
      'MEMBRO_SUP_ESQ',
      'QUADRIL',
      'CERVICAL',
      'MACA_SOBRE_RODAS',
      'MACA_RIGIDA',
      'PONTE',
      'RETIRADO_CAPACETE',
      'RCP',
      'ROLAMENTO_90',
      'ROLAMENTO_180',
      'TOMADA_DECISAO',
      'TRATADO_CHOQUE',
      'USO_DE_CANULA',
      'USO_KED',
      'USO_TTF',
      'VENTILACAO_SUPORTE',
      'MEIOS_AUXILIARES',
      'CELESC',
      'DEF_CIVIL',
      'IGP_PC',
      'CIT',
      'ANOTHER',
      'USO_COLAR_TAM',
      'OXIGENOTERAPIA',
      'REANIMADOR',
      'SAMU',
      'POLICIA',
    ]),
    sizes: z.string().nullable().default(null),
    LPM: z.number().nullable().default(null),
    options: z.array(z.string()).default(['']),
  }),
  MateriaisDescartaveis: z.object({
    state: z.boolean().nullable(),
    name: z.enum([
      'ATADURAS',
      'KITS',
      'LUVAS_DESC_PARES',
      'TALAS_PAP',
      'CATETER_TP_OCULOS',
      'COMPRESSORA_COMUM',
      'MASCARA_DESC',
      'MANTA_ALUMINIZADA',
      'PAS_DO_DEA',
      'SONDA_DE_ASPIRACAO',
      'SORO_FISIOLOGICO',
    ]),
    quantity: z.number().nullable(),
    sizes: z.array(z.string()).nullable(),
  }),

  MateriaisDeixadosNoHospital: z.object({
    state: z.boolean().nullable(),
    name: z.enum([
      'COLAR',
      'KED',
      'TTF',
      'BASE_DO_ESTABILIZA',
      'COXINS_ESTABILIZA',
      'MACA_RIGIDA',
      'TIRANTE_ARANHA',
      'TIRANTE_DE_CABECA',
      'CANULA',
    ]),
    quantity: z.number().nullable(),
    sizes: z.array(z.string()).nullable(),
  }),
})
export const updateInfosHospitalares = z.object({
  reportId: z.number(),
  Doctor: z.string().optional(),
  S1: z.string().optional(),
  S2: z.string().optional(),
  S3: z.string().optional(),
  Demandant: z.string().optional(),
  TeamUp: z.string().optional(),
  ProcedimentosEfetuados: z.object({
    state: z.boolean().nullable().optional(),
    name: z
      .enum([
        'ASPIRACAO',
        'AVALIACAO_INICIAL',
        'AVALIACAO_DIRIGIDA',
        'AVALIACAO_CONTINUADA',
        'CHAVE_DE_RAUTEK',
        'CANULA_DE_GUEDEL',
        'DESOBSTRUCAO_DE_VA',
        'EMPREGO_DO_DEA',
        'GERENCIAMENTO_DE_RISCOS',
        'LIMPEZA_DE_FERIMENTO',
        'CURATIVOS',
        'COMPRESSIVO',
        'ENCRAVAMENTO',
        'OCULAR',
        'QUEIMADURA',
        'SIMPLES',
        'THREE_PONTAS',
        'IMOBILIZACOES',
        'MEMBRO_INF_DIR',
        'MEMBRO_INF_ESQ',
        'MEMBRO_SUP_DIR',
        'MEMBRO_SUP_ESQ',
        'QUADRIL',
        'CERVICAL',
        'MACA_SOBRE_RODAS',
        'MACA_RIGIDA',
        'PONTE',
        'RETIRADO_CAPACETE',
        'RCP',
        'ROLAMENTO_90',
        'ROLAMENTO_180',
        'TOMADA_DECISAO',
        'TRATADO_CHOQUE',
        'USO_DE_CANULA',
        'USO_KED',
        'USO_TTF',
        'VENTILACAO_SUPORTE',
        'MEIOS_AUXILIARES',
        'CELESC',
        'DEF_CIVIL',
        'IGP_PC',
        'CIT',
        'ANOTHER',
        'USO_COLAR_TAM',
        'OXIGENOTERAPIA',
        'REANIMADOR',
        'SAMU',
        'POLICIA',
      ])
      .nullable()
      .optional(),
    sizes: z.string().nullable().default(null).optional(),
    LPM: z.number().nullable().default(null).optional(),
    options: z.array(z.string()).optional(),
  }),
  MateriaisDescartaveis: z.object({
    state: z.boolean().nullable(),
    name: z
      .enum([
        'ATADURAS',
        'KITS',
        'LUVAS_DESC_PARES',
        'TALAS_PAP',
        'CATETER_TP_OCULOS',
        'COMPRESSORA_COMUM',
        'MASCARA_DESC',
        'MANTA_ALUMINIZADA',
        'PAS_DO_DEA',
        'SONDA_DE_ASPIRACAO',
        'SORO_FISIOLOGICO',
      ])
      .optional()
      .nullable(),
    quantity: z.number().nullable(),
    sizes: z.array(z.string()).nullable(),
  }),

  MateriaisDeixadosNoHospital: z.object({
    state: z.boolean().nullable(),
    name: z.enum([
      'COLAR',
      'KED',
      'TTF',
      'BASE_DO_ESTABILIZA',
      'COXINS_ESTABILIZA',
      'MACA_RIGIDA',
      'TIRANTE_ARANHA',
      'TIRANTE_DE_CABECA',
      'CANULA',
    ]),
    quantity: z.number().nullable(),
    sizes: z.array(z.string()).nullable(),
  }),
})
